name: lint
on:
    push:
        branches: ['master', 'development']
jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node-version }}

            - name: npm install
              run: npm ci

            - name: Run linter
              run: npm run lint

            - name: Trigger unit tests
              if: success()
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.DOCKER_PASSWORD }}
                  repository: ${{ github.repository }}
                  event-type: trigger-unit-tests
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
