# name: Docker
# on:
#     push:
#         branches: ['master', 'development']
# jobs:
#     lint:
#         runs-on: ubuntu-latest
#         strategy:
#             matrix:
#                 node-version: [16.x]
#         steps:
#             - uses: actions/checkout@v2
#             - uses: actions/setup-node@v2-beta
#               with:
#                   node-version: ${{ matrix.node-version }}
#             - name: npm install
#               run: npm ci
#             - name: Run linter
#               run: npm run lint

#     unit-tests:
#         runs-on: ubuntu-latest
#         needs: [lint]
#         strategy:
#             matrix:
#                 node-version: [16.x]
#         steps:
#             - uses: actions/checkout@v2
#             - uses: actions/setup-node@v2-beta
#               with:
#                   node-version: ${{ matrix.node-version }}
#             - name: npm install
#               run: npm ci
#             - name: Run unit tests
#               run: npm run test

#     e2e-tests:
#         runs-on: ubuntu-latest
#         needs: [unit-tests]
#         strategy:
#             matrix:
#                 node-version: [16.x]
#                 mongodb-version: ['4.4.4']
#         steps:
#             - uses: actions/checkout@v2
#             - uses: actions/setup-node@v2-beta
#               with:
#                   node-version: ${{ matrix.node-version }}
#             - name: Start MongoDB
#               uses: supercharge/mongodb-github-action@1.6.0
#               with:
#                   mongodb-version: ${{ matrix.mongodb-version }}
#             - name: npm install
#               run: npm ci
#             - name: Run run e2e tests
#               run: npm run test:e2e
#               env:
#                   USE_LOCAL_MONGO_HOST: true

#     build:
#         runs-on: ubuntu-latest
#         needs: [e2e-tests]
#         steps:
# - uses: actions/checkout@master
# - name: Publish to registry
#   uses: elgohr/Publish-Docker-Github-Action@master
#   with:
#       registry: docker.pkg.github.com
#       name: docker.pkg.github.com/wavilikhin/nest-api/nest-api
#       username: ${{ secrets.DOCKER_USERNAME }}
#       password: ${{ secrets.DOCKER_PASSWORD }}
#       tags: development
