name: Docker
on:
    push:
        branches: ['master', 'development']
jobs:
    build:
        runs-on: ubuntu-latest
        # needs: [lint]
        steps:
            - uses: actions/checkout@master
            - name: Publish to registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/wavilikhin/nest-api/nest-api
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tags: 'develop'
        # unit-tests:
        #     runs-on: ubuntu-latest
        #     strategy:
        #         matrix:
        #             node-version: [14.x, 16.x]
        #     steps:
        #         - uses: actions/checkout@v2
        #         - name: Use NodeJS ${{ matrix.node-version }}
        #           uses: actions/setup-node@v1
        #           with:
        #               node-version: ${{ matrix.node-version }}
        #         - name: npm install
        #           run: npm ci
        #         - name: npm test
        #           run: npm run test
        # e2e-test:
        #     runs-on: ubuntu-latest
        #     strategy:
        #         matrix:
        #             node-version: [16.x]
        #             # node-version: [14.x, 16.x]
        #     # needs: [unit-tests]
        #     steps:
        #         - uses: actions/checkout@v1
        #         - name: Login into github docker registry
        #           run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        #         - name: Use Node.js ${{ matrix.node-version }}
        #           uses: actions/setup-node@v1
        #           with:
        #               node-version: ${{ matrix.node-version }}
        #         - name: Start Docker-Compose
        #           run: docker-compose up -d
        #         - name: npm install
        #           run: npm ci
        #         - name: Run tests
        #           run: npm run test:e2e
        #         - name: Stop Docker-Compose
        #           run: docker-compose down
        # lint:
        #     runs-on: ubuntu-latest
        #     strategy:
        #         matrix:
        #             node-version: [14.x, 16.x]
        #     needs: [e2e-test]
        #     steps:
        #         - name: Lint ts
        #         - uses: actions/checkout@v2
        #         - uses: actions/setup-node@v2-beta
        #           with:
        #               node-version: ${{ matrix.node-version }}
        #         - name: npm install
        #           run: npm ci
        #         - name: Run tests
        #           run: npm run test:e2e
