name: Lint, test and publish Docker image

on:
    push:
        branches: [master]
jobs:
    lint:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: 16

            - run: npm install
            - run: npm run lint
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: 16

            - run: npm install
            - run: npm run test
            - run: npm run test:e2e
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Publish to registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/wavilikhin/nest-api/nest-api
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tags: 'develop'
