name: unit tests
on:
    workflow_dispatch:
        inputs:
            trigger_next:
                description: 'Whether to run the subsequent workflows after triggering this one manully.'
                required: false
                default: false
    repository_dispatch:
        types: [trigger-workflow-2]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.client_payload.sha }}

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node-version }}

            - name: npm install
              run: npm ci

            - name: Run unit tests
              run: npm run test

            - uses: r-lib/actions/setup-r@master

            - uses: r-lib/actions/setup-pandoc@master
